import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import '@fontsource/poppins'; // Requires `npm install @fontsource/poppins`
import "./globals.css";

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: "400",
//   variable: "--font-poppins",
//   display: "swap", // better font loading performance
// });

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="font-sans antialiased">
        {children}
      </body>
    </html>
  );
}